### PR TITLE
Fix broken sharding

### PR DESCRIPTION
**Pull request by LesterTheTester**
Whoops.  Used the wrong variable for sharIndex.  This should fix it

### CODE REVIEW

**Comment by LesterTheTester** [comment]
This is why I'm "LesterTheTester" and not "LesterTheDeveloper" :chicken:

**Comment by edenman** [comment]
I guess nobody else was really using sharding yet, huh? :)

**Comment by edenman** [comment]
Rolling a 1.5.1 release now, should be up soon

**Comment by edenman** [comment]
(you broke my shard) 💔

**Comment by LesterTheTester** [comment]
I've got another PR coming (hopefully) that cleans up the look of the index file too. Sorry to make you roll twice :(

**Comment by edenman** [comment]
No worries, thanks for the fixes!

**Pull request merged**
