### PR TITLE
Android Marshmallow compatibility

### PR DESCRIPTION
**Pull request by robertdolca**
Grant external storage permissions with adb. #292

### CODE REVIEW

**Comment by JakeWharton** [comment]
Part of this is covered in https://github.com/square/spoon/pull/306

**Comment by robertdolca** [comment]
I've dropped one of the commits. Thanks @JakeWharton

**Comment by edenman** [comment]
Thanks, @robertdolca!

**Comment by Kiran89kumar** [comment]
issue is still seen in 1.6.4

**Comment by developers-bhagini** [comment]
This issue is still seen in 1.7.0 any updates on this?

**Comment by AronRaj** [comment]
Issue is still present in 1.7.0 as well . Used Nexus 6 with Android 7.0
Failed with Exception
Cause=java.lang.IllegalAccessException: Unable to create output dir: /storage/emulated/0/app_spoon-screenshots/
DetailMessage=Unable to capture screenshot.

**Comment by tnainani** [comment]
Issue still present in 'com.squareup.spoon:spoon-client:1.7.1'?

**Pull request merged**
