### PR TITLE
Add save files ability to SpoonRule.

### PR DESCRIPTION
**Pull request by dweebo**
As discussed in #465

Basically just copied over code from old `Spoon.java` implementation w/ minor changes to `SpoonRule`, and clear files from each device at the start of testing.

Question: Should the code in `SpoonRule` have tests?  I see we don't have Mockito or PowerMock so it would be difficult unless we move androidy stuff out to separate classes.

### CODE REVIEW

**Comment by edenman** [comment]
Yeah, we definitely don't want to use Mockito/etc.  My guess is that writing tests for SpoonRule would be more effort than it's worth, given how entangled it all is with Android, but feel free to take a crack at it.

**Comment by CAH-peterhewitt** [comment]
Just curious to hear why you are against Mockito?  We use it heavily for our android tests and frequently mock out android classes.  It is not fun but it works.  Would love to hear a better alternative.

**Comment by JakeWharton** [comment]
Mocking is a vehicle to coupling tests to implementation details. I prefer
testing strategies which force good design instead of encourage coupling.
For example, the use of fakes necessitate a design that allows dependencies
to be swapped and discourages reliance on the order of things called
(instead relying on emulated behavior and not caring how it's called).

**Comment by dweebo** [comment]
Thanks Jake, I agree with it coupling to implementation, we fight that quite a bit.  Android just makes it so tough to do.  Appreciate the response.

**Pull request merged**
