### PR TITLE
Updated amxlparser to handle UTF-8 encoded manifest files.

### PR DESCRIPTION
**Pull request by MonteCreasor**
New pull request with changes in a branch instead of on master (please ignore closed pull on master). 

This branch has the amxlparser changes to handle UTF-8 along with JUnit tests and two small test APKs to verify both UTF-8 and UTF-16 parsing.

### CODE REVIEW

**Comment by gbourassa** [comment]
For what it's worth, I tried your code and it seem to correctly fix the parsing issue with gradle plugin 3.0 (https://github.com/square/spoon/issues/461).  I'd be happy to have this integrated :)

However, the master branch seems to be very far in a new direction, having a hotfix on the current version would be better (and I have no idea how close to release version 2.0 is).

**Comment by MonteCreasor** [comment]
Sure, no problem. If it's ok with you, I'll look into that tomorrow or on
Thursday. I've never done a hot fix so I just googled it, but I'm not sure
that what I read is exactly what you want. So, if you have the time, please
give me a brief description of the steps I need to take to give you the
update code as a hot fix.

Thanks,
Monte

**Comment by gbourassa** [comment]
I don't really know how they manage the release cycle for this lib.
Maybe @JakeWharton could point you in the right direction?

**Comment by JakeWharton** [comment]
This project is not used by Square and I'm not longer at Square. So it's
now a hobby at best.

**Comment by MonteCreasor** [comment]
Don't worry about it. I'll just do a fresh clone, merge my changes in, and
then make a new pull request.

**Comment by gbourassa** [comment]
I guess that having the fix in 2.0.0 is better than nothing.

I understand that you don't really have time for this lib anymore @JakeWharton. Can you at least give us an idea on how close to a release 2.0.0 is? Were there a lot of things left to do before you consider it "done"?

**Comment by JakeWharton** [comment]
As far as a 2.0, it's pretty far along. The only public API is the CLI and
the SpoonRunner.Builder or whatever it's called. So as long as that's
stable we can release 2.0 and things like making the output not look like
it's 5 years old can be done after.

**Comment by MonteCreasor** [comment]
Guillaume,

I finally have time to redo the pull request. Do you want me to redo it from the latest version of master? If so, it's trivial to do since the only changes I made were in axmlparser which hasn't changed for 7 months, so it's just a copy/paste solution.

**Comment by gbourassa** [comment]
Starting from master to do the fix would make sense, especially if 2.0 is to be released soon.

**Comment by MonteCreasor** [comment]
I added a new pull request yesterday.

**Pull request closed without merging**
