### PR TITLE
Added support for UTF-16 encoded Android Studio 3 manifest format.

### PR DESCRIPTION
**Pull request by MonteCreasor**
Guilluame,

I added my fix over the latest master version and tested it so you can merge it now.

### CODE REVIEW

**Comment by gbourassa** [comment]
_The Travis CI build failed_  ... this doesn't look normal :)

**Comment by MonteCreasor** [comment]
Fixed it. I had moved the test APKs from the last pull request to a more appropriate location in the test resources directory which Intellij IDE can find with right-click "Run tests..." but gradle's test task can't find. So I added code in the test class that will find the test APKs in both cases.

**Comment by saruye** [comment]
Hi. thanks for fixing this so fast! 
Is there any eta for when there will be a new release with this fix? Should we create our own build and use that. Or is it worth waiting for an official release?

**Comment by edenman** [comment]
@saruye https://github.com/square/spoon/issues/461#issuecomment-333612313

**Pull request merged**
