### PR TITLE
Use adbTimeout to prevent timeout on apk install on device (square #176 )

### PR DESCRIPTION
**Pull request by intelradoux**
Got timeout when 10 devices are connected to a hub linked to my computer. This is a fix.

### CODE REVIEW

**Comment by edenman** [comment]
LGTM, thanks for resubmitting.  Can you please sign our [CLA] (https://docs.google.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ) and then I'll merge.

**Comment by edenman** [comment]
@intelradoux ping

**Comment by intelradoux** [comment]
pong   (CLA done)

**Comment by edenman** [comment]
Thanks!

**Pull request merged**
