### PR TITLE
Added sequential functionality (run tests on one device at a time)

### PR DESCRIPTION
**Pull request by olivierg13**
Hello,

This is a pull request for doing a sequential execution (run tests device by device).
I used SquareAndroid code style with IntelliJ. 2 lines seem to have changed into SpoonRunner, but seem to respect your code style better (were modified before?).
I use an ExecutorService, constructed thanks to Executors.newSingleThreadExecutor().

The principle of the CountDownLatch is still intact, it simply runs on the ExecutorService if "sequential" is set to true, and runs on a normal Thread otherwise.

I modified both the SpoonRunner.Builder() and the RunMojo Maven Plugin to get the parameter (thanks to the argument --sequential or -Dsequential).

Cheers,

Olivier Goutay

### CODE REVIEW

**Comment by edenman** [comment]
@olivierg13 I'm going through old Spoon PRs now and this one looks good.  It needs a rebase and then I'm happy to merge it.  You'll need to sign the [Square CLA] (https://docs.google.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ) too.

**Comment by olivierg13** [comment]
Hello @edenman 

I just rebased the branch with upstream/master, the Tests passed and the project runs smoothly.
I also signed the Square CLA.

Don't hesitate to contact me if you need anything.

Thanks in advance.

Cheers,

Olivier

**Comment by edenman** [comment]
Cool! Can you squash your commits please?

**Comment by olivierg13** [comment]
@edenman No problem, I just squashed the two last commits. Impossible to squash the merge with master though (which is probably normal).

**Comment by edenman** [comment]
Thanks @olivierg13.  I'm struggling to get the project built, hoping to release this soon.

**Comment by olivierg13** [comment]
@edenman Thanks again. Do not hesitate if you need something from me :)
Do you know if you are going to migrate this project to gradle at one point?

**Comment by edenman** [comment]
@olivierg13 considering how difficult it's proving to get the maven build working, a gradle conversion might happen sooner rather than later :/  Probably not til next week at the earliest, though.

**Comment by olivierg13** [comment]
@edenman No problem, it was just to know, it's true that's easier on gradle (especially when you are on Android Studio). Thanks in advance!

**Pull request merged**
