### PR TITLE
Better handling of double results

### PR DESCRIPTION
**Pull request by LesterTheTester**
In issue #370, we noticed that there are some circumstances where the TestRunListener can get more than one testFailed event.  My fix wasn't good enough, it just pushed the problem down the chain since we'd fail on the second testEnded.  This still produced the undesired behaviour of failing to generate an xml report for the run.

This PR cleans that up, adds error logging when it occurs, and rips out everything related to Status.Error, which we discovered isn't used by JUnit anymore.

### CODE REVIEW

**Comment by LesterTheTester** [comment]
I'm gonna run this in my environment to make sure it really fixes it this time, hold off on merging for a sec

**Comment by edenman** [comment]
👍

**Comment by LesterTheTester** [comment]
Tested and ready to go.  Thanks for waiting.

**Comment by edenman** [comment]
@LesterTheTester 1.6.4 pushed to mvn central.

BTW, i'm out from 8/15-8/29 so if you break anything else you're on your own :P

**Pull request merged**
