### PR TITLE
Capture Dialogs

### PR DESCRIPTION
**Pull request by mandrachek**
Adds the ability to create an image from a view (uses the view root), allowing for the capture of dialogs.

When capturing a dialog, it doesn't get the main application window, and it doesn't record the relative position of the dialog on the screen.

I've also created an Espresso ViewAction, <a href="https://gist.github.com/mandrachek/d8048795f600515c25a5">SpoonDialogAction</a> based on <a href="https://gist.github.com/edenman/7fdd32a4d59ccc01185b">SpoonScreenshotAction</a>, which you can call like so: `SpoonDialogAction.perform(withId(R.id.field_in_dialog), "my_dialog");`

### CODE REVIEW

**Comment by JakeWharton** [comment]
Hesitant about this API. I'd rather use the reflection hack to walk over the windows or use the instrumentation API. What other cases are there for capturing a subset of the views?

**Comment by mandrachek** [comment]
I don't have any myself - just needed to be able to grab dialogs for an app at work. Discovered #4 via way of #66 , whipped this up in a few minutes which scratched my itch and thought I'd share it. 

Doing it this way does have _some_ advantages, as doesn't use any private APIs, is very backwards compatible, and from what I can tell - doesn't seem to mess up the animated gifs.

By reflection hack you mean accessing the WindowManagerGlobal  (http://stackoverflow.com/questions/19669984/android-is-there-a-way-to-programmatically-locate-all-windows-within-a-given-a) or the one by @RichardGuion mentioned in #4?  

And by the instrumentation api, I assume you mean the Instrumentation.getUiAutomation().takeScreenshot()?

I would think at least both would be necessary to handle backwards compatibility, given the api 18 requirement for the instrumentation method.

I'd be happy to take a crack at combining these.

**Comment by mandrachek** [comment]
I've got this basically working. Uses UiAutomator by default (a flag is provided to turn it off if it causes problems for you), falls back to walking the window hierarchy using reflection, and if all else fails, it falls back to getting the decor view of the activity like it does currently

I've run into one small problem with my testing, and I'm not sure this is spoon's problem per se, more of an Espresso thing. With either UiAutomation or reflection, my SpoonViewAction is giving me screenshots with an empty window - the root view, which just displays my window background color.

I tried adding a call to uiController.loopMainThreadUntilIdle(); but that didn't help. I tried adding a SystemClock.sleep(100);, and that resolved the issue, but that's device dependent, and so is fragile.

The way to ensure the ui is drawn is to provide a matcher to a custom view in your ui, which it will then wait for before attempting to take the screenshot.

```
public static void perform(String tag, Matcher matcher, boolean useUiAutomator) {
    StackTraceElement[] trace = Thread.currentThread().getStackTrace();
    String testClass = trace[3].getClassName();
    String testMethod = trace[3].getMethodName();
    onView(matcher).perform(new SpoonScreenshotAction(tag, testClass, testMethod, useUiAutomator));
  }
```

Sound good?

**Comment by mandrachek** [comment]
@JakeWharton I'd like to commit this and send it on over, but it's dependent on compiling against Android 4.3 for the UiAutomator.  The project is currently configured to use the 4.1.1.4 sdk libs in maven, and there doesn't appear to be a newer version deployed there.  I've deployed my own copy locally and updated the pom, but I don't know if that's how you want to go with this, since it would break builds for anybody who hasn't done so.  

Please let me know how, or if, you'd like me to proceed.

**Comment by rafaelaazevedo** [comment]
Any news about this one ? I am using robotium with spoon and I am having the same problem

**Comment by pvegh** [comment]
How cool, I'd love to see this merged!

**Comment by ObjectiveTruth** [comment]
Any new news on this? This library is so good, can't help but want more :joy:

**Comment by adheesh24** [comment]
Hi,
I want to take screenshots of dialogs in my application. Read many issues but wasn't able to figure a way to do it. I take the screenshot in the following way.
Spoon.screenshot(activity, tag);
But the screenshot of activity gets captured in index.html.
Can anyone help me do it? Does spoon still doesn't support taking screenshots of dialog?

Thanks.

**Comment by ligi** [comment]
you can use com.jraska:falcon-spoon-compat - https://github.com/jraska/Falcon

**Pull request closed without merging**
