### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by tir38**
While poking around I noticed these lines were not used.

### CODE REVIEW

**Comment by tir38** [comment]
I don't know why Github is including commits from a previous PR, even though the changes don't show up in the list of "file changed".

**Comment by edenman** [comment]
@tir38 might need to [sync](https://help.github.com/articles/syncing-a-fork/) your fork?

**Comment by edenman** [comment]
LG.  Comment here after you try syncing and I'll merge.

**Comment by tir38** [comment]
Hmm yeah I did that. That's why the code changes are correct. Is it possible this is just a weird github aberration?

**Comment by edenman** [comment]
Yeah, totally possible.  Thanks for trying (and for the PR!)

**Pull request merged**
