### PR TITLE
Bumped ddmlib version from 24.5.0 to 25.1.2

### PR DESCRIPTION
**Pull request by kirillzh**
Solves #302 [issue](https://code.google.com/p/android/issues/detail?id=195998).
`Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of system`

### CODE REVIEW

**Comment by edenman** [comment]
Excellent, thanks @kirillzh!  I knew somebody would eventually figure it out :)

Can you please sign the [Square CLA](https://docs.google.com/forms/d/13WR8m5uZ2nAkJH41k7GdVBXAAbzDk00vxtEYjd6Imzg/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ) and let me know here when you've done so?

**Comment by kirillzh** [comment]
Sure, signed it!

Thanks, @edenman.

**Comment by kirillzh** [comment]
@edenman, I am not sure why CI build failed.

**Comment by edenman** [comment]
It's bc I merged the thing before it had a chance to pull your branch, I think.  The java7 one passed and that's good enough for me :)

**Comment by kirillzh** [comment]
Great then!

**Comment by edenman** [comment]
1.5.7 released, should be live in a couple hours.  Thanks again @kirillzh!

**Comment by kirillzh** [comment]
Glad to help. Thank you for quick merge, @edenman!

**Pull request merged**
