### PR TITLE
Screenshot directory clean bugfix

### PR DESCRIPTION
**Pull request by dweebo**
Bugfix for issue discussed in #478 

Tested on emulators and real devices, including kitkat (screenshots in internal storage).

### CODE REVIEW

**Comment by edenman** [comment]
LGTM, just need the CLA signed.  LMK when you've signed it

**Comment by dweebo** [comment]
I just signed the CLA

**Comment by mbmc** [comment]
Using the latest (dbccd11cb194505b27fd4faf2b91db59a777ef1f), I still see only 1 screenshot after completion. Also, the coverage doesn't seem to be working anymore.

**Comment by dweebo** [comment]
@mbmc I am not sure what the issue is, it is working for me fine on my projects.  How are you getting the snapshot version into your project? and how are you running spoon?

As a sanity check you can run the test-app that is included in spoon to see if the screenshots show up there in multiple tests.  run `./gradlew spoonAndroidTest`

**Pull request merged**
