### PR TITLE
mentioning a possible solution in the exception when spoon failed to …

### PR DESCRIPTION
**Pull request by jainsahab**
…pull the coverage file

### CODE REVIEW

**Comment by edenman** [comment]
@jainsahab thanks!  looks like checkstyle is unhappy :/

**Comment by jainsahab** [comment]
It is happy now. :)

**Comment by jainsahab** [comment]
fun trivia is, Pull request number is 404 when spoon could not find the coverage file.

**Comment by edenman** [comment]
@jainsahab omg

**Pull request merged**
